# Generated by Django 5.0.6 on 2024-06-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albummodel',
            old_name='Album_Name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='albummodel',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='albummodel',
            old_name='Release_Date',
            new_name='release_date',
        ),
    ]
