# Generated by Django 5.0.6 on 2024-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_rename_album_name_albummodel_album_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumModel',
        ),
    ]
