# Generated by Django 5.0.6 on 2024-06-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='Instrument_Type',
            new_name='instrument_type',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
    ]
